version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      
  mongodb:
    image: mongo:latest  # Образ MongoDB
    container_name: mongodb_container  # Название контейнера
    ports:
      - "27017:27017"  # Проброс порта для доступа к MongoDB с хоста
    volumes:
      - mongo_data:/data/db  # Сохранение данных в volume

volumes:
  mongo_data:
  mongo_config:
